### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by molarmanful** [RYDLAB/jagc.org#11]
I'm thinking CJam, GolfScript, etc. or just an option to specify a custom language.

Perhaps this might ruin the fun, but it's a suggestion.

**Comment by avkhozov** [comment]
Yes, it would be nice. Can you specify full list of this languages, and their versions, if this is matter?

**Comment by molarmanful** [comment]
Wow, there's a lot...
- CJam
- Pyth
- GolfScript, GS2
- Befunge
- ><> (Fish)
- APL, J, and K
- Julia
- Mathematica
- MATLAB
- Retina
I'm sure there are a lot more that could be added. I'm going to need some help with compiling this list.

**Comment by avkhozov** [comment]
Thanks, I will add this languages after migration from lxc to docker.

**Comment by avkhozov** [comment]
@mw26 added a few languages, you can see its on http://jagc.org/about.  Now we have 15 popular languages.

For new languages pull requests are welcome. Commands in Dockerfile (https://github.com/RYDLAB/jagc.org/blob/master/Dockerfile) and example for "A + B" task (http://jagc.org/examples) will be enough.
