### ISSUE TITLE
How does one start the API server?

### ISSUE THREAD

**Issue by sidoh** [RYDLAB/jagc.org#12]
Hey,

Thanks very much for putting this project up. It's awesome.

I'm looking to host a code golf tournament for my company, and I was hoping to install this on my server. 

I'm able to start the web server and the minion workers, but there seems to be another component configured here:

```
  worker => {
    api_server        => 'http://localhost:2375',
```

This appears to be responsible for running user submitted code in docker containers. I'm having a hard time figuring out how this piece is started. Are you able to offer some insight?

**Comment by avkhozov** [comment]
Hi Chris, thanks for feedback.

You need to start docker daemon with tcp listen socket (https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-socket-option).

If you use systemd as init system you might want to override system ``docker.service`` like this:
```bash
# cat /etc/systemd/system/docker.service.d/override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -H tcp://127.0.0.1:2375
```

**Comment by sidoh** [comment]
Aah -- this makes sense. I probably should've realized that, but I've not messed around with Docker much.

Thanks for your help!
