### ISSUE TITLE
Please abandon Golfscript on JAGC.org

### ISSUE THREAD

**Issue by vakorol** [RYDLAB/jagc.org#13]
I sent an email with the same text to info@jagc.org, but actually it may be better to  raise the question for public discussion:

As a long-time participant at jagc.org, i would suggest removing "golfscript" from the list of available languages, and dismissing all current results achieved using that language. The reason  is that it is totally destroying all the fun one could get from a golfing contest. I always envisioned such activities as a possibility for people (especially professional developers/programmers) to get pleasure by employing their skills in programming in their free time. Unfortunately, after golfscript was introduced, it is has been all about learning a useless language which is designed only for "golfing". The whole list of other languages offered at jagc.org is now useless, because in 99% cases it is impossible to beat golfscript.

Right now i don't see the point in participating in further activity. If you prefer to keep things as they are now, i think it makes sense to remove all other languages from the list and make jagc a golfscript playground only.

**Comment by k-mx** [comment]
I think that split stats for general purpose and golf languages will be harder but better solution.

**Comment by k-mx** [comment]
You can restrict list of languages with [contests](http://jagc.org/contests).
